# -- Theme Options --
# These options control how the theme functions and allow you to customize the display of your website.
# Refer to the theme docs for more details about each of these parameters.
# https://mnjm.github.io/kayal/docs/configuration/#theme-parameters

# [Optional] Path to the site logo image relative to assets/ folder. Displayed before the Site Title in the header. Minimum size: 64x64px.
# logo = "/imgs/logo.png"
# Site description.
description = "A Hugo Theme"
# [Optional] Copyright owner name.
copyright = "Copyright Inkresi."
# Whether to optimize images per view port.
optimizeImg = true
# Whether to enable copy button in code blocks.
enableCodeCopy = true
# Show the icon that switches between dark and light themes when clicked.
showThemeSwitcher = true
# Default theme to start from. If "auto", it detects the previous preference/system theme.
defaultTheme = "auto"  # Valid Options: light, dark, auto
# When enabled, highlight the current menu item in the menu bar.
highlightCurrentMenu = true
# The sections to display in the recent articles list. If not provided, the section with the most articles is used.
mainSections = ["posts"]
# Whether to remove Hugo and theme attribution in the footer.
removeAttribution = false
# Whether to show anchor links in headings. Can be overridden by Page-specific `showHeadingAnchors` in its front matter.
showHeadingAnchors = true
# Whether to enable search. Needs JSON output for this to work.
enableSearch = true

# Site search engine verification tags.
# [verification]
# google = ""
# bing = ""
# pinterest = ""
# yandex = ""

# Homepage settings
[homepage]
# Whether to show recent items on the homepage.
showRecent = true
# Heading label for recent items.
showRecentLabel = "Featured"
# Number of recent items to show.
showRecentItems = 4
# Whether to display a "Show more" link at the end of recent section that directs to `showMoreDest`.
showMore = true
showMoreDest = "/posts"
[homepage.profile]
# [Optional] Displayed at the top of your homepage.
headline = "ğŸ‘‹ Welcome to my site"
# [Optional] Path to the profile image relative to assets/ folder. Minimum size: 200x200px.
description = "ä½ å¥½ï¼Œæˆ‘æ˜¯è’‹å¤§åŸ¹ã€‚æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸ªäººåšå®¢ï¼æˆ‘æ˜¯ä¸€åçƒ­çˆ±è½¯ä»¶å¼€å‘çš„å·¥ç¨‹å¸ˆï¼Œè¿™ä¸ªåšå®¢æ˜¯æˆ‘ä¸ä½ åˆ†äº«æŠ€æœ¯è§è§£ã€æºç é˜…è¯»å¿ƒå¾—ä»¥åŠå¯¹äºæŠ€æœ¯çš„æ·±å…¥ç†è§£çš„å¹³å°ã€‚åœ¨è¿™é‡Œï¼Œæˆ‘ä¼šåˆ†äº«æˆ‘çš„ç¼–ç¨‹æ—…ç¨‹ï¼Œè®°å½•æˆ‘åœ¨æ¢ç´¢ä»£ç ä¸–ç•Œæ—¶çš„ç‚¹æ»´ä½“ä¼šã€‚æ— è®ºæ˜¯æœ€æ–°çš„æŠ€æœ¯è¶‹åŠ¿ã€ä»£ç ä¼˜åŒ–çš„æŠ€å·§è¿˜æ˜¯å¯¹äºè½¯ä»¶å¼€å‘è¿‡ç¨‹ä¸­çš„æŒ‘æˆ˜å’Œè§£å†³æ–¹æ¡ˆï¼Œæˆ‘éƒ½ä¼šå°½å¯èƒ½åœ°å°†æˆ‘çš„å¿ƒå¾—ä½“ä¼šä¸ä½ åˆ†äº«ã€‚å¦‚æœä½ å¯¹äºæŸä¸ªç‰¹å®šä¸»é¢˜æ„Ÿå…´è¶£ï¼Œä¹Ÿæ¬¢è¿åœ¨è¯„è®ºåŒºç•™è¨€ï¼Œæˆ‘ä»¬ä¸€èµ·æ¢è®¨ã€äº¤æµï¼Œå…±åŒè¿›æ­¥ã€‚é™¤äº†æŠ€æœ¯åˆ†äº«ï¼Œæˆ‘è¿˜ä¼šä¸å®šæœŸåœ°å‘å¸ƒä¸€äº›ç”Ÿæ´»æ„Ÿæ‚Ÿã€è¯»ä¹¦ç¬”è®°ç­‰å†…å®¹ï¼Œå¸Œæœ›èƒ½å¤Ÿåœ¨æŠ€æœ¯æ¢ç´¢çš„åŒæ—¶ï¼Œä¸ä½ åˆ†äº«æ›´å¤šå…³äºç”Ÿæ´»çš„ç¾å¥½ä¸æ€è€ƒã€‚"
image = "images/acva.jpg"
# Image position.
where = "right"  # Options: right, left, top

# Article settings
[article]
# Whether to display article dates.
showDate = true
# Whether to display modified dates of articles.
showModDate = true
# Whether to display reading time of articles.
showReadingTime = true
# Whether to display tags mentioned in the front matter.
showTags = true
# Whether to display next/previous article links in the article footer.
showPagination = true
# Whether to reverse the direction of next/previous article links.
invertPagination = true
# Whether to display the table of contents on articles.
showToC = true
# Whether to open the Table of Contents when the page is loaded.
openToC = false
# Check https://mnjm.github.io/kayal/docs/advanced-customization/#comments
showComments = false
# Whether to display breadcrumbs
showBreadcrumbs = true

# List template settings
[list]
# Whether to group articles by year.
groupByYear = false
# Whether to display breadcrumbs
showBreadcrumbs = true
# Whether to display pages as a card
cardView = true
# Whether to display RSS link
showRSS = false

# Taxonomy settings
[taxonomy]
# Whether to show counts of each taxonomy term.
showCount = true
# Whether to display taxonomies as a grid of cards.
cardView = true

# Term settings
[term]
# Whether to group articles by year.
groupByYear = false
# Whether to display breadcrumbs
showBreadcrumbs = false
# Whether to display pages as a card
cardView = true
# Whether to display RSS link
showRSS = false

# Social links
# [[social]]
# name = "GitHub"
# icon = "github"
# url = "https://github.com/mnjm/kayal"
#
# [[social]]
# name = "Email"
# icon = "email"
# url = "mailto:name@example.com"
#
# [[social]]
# name = "Twitter / X"
# icon = "x-twitter"
# url = "https://x.com/sample"
